# Generated by Django 2.2.10 on 2020-06-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crazysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
